### ISSUE TITLE
speed comparison with cv2.imread

### ISSUE THREAD

**Issue by laisimiao** [ajkxyz/jpeg4py#7]
Does ipeg4py load image faster than cv2.imread? Because in my project, there are many image load operations and image enhancement. I did a small test, is it right?
```python
import cv2
import time
import jpeg4py as jpeg
import matplotlib.pyplot as pp
cv2.ocl.setUseOpenCL(False)
cv2.setNumThreads(0)


if __name__ == "__main__":
    tic = time.clock_gettime(time.CLOCK_PROCESS_CPUTIME_ID)
    jpeg_img = jpeg.JPEG("/home/lz/Pictures/scene.jpg").decode()
    print(time.clock_gettime(time.CLOCK_PROCESS_CPUTIME_ID)- tic)
    tic = time.clock_gettime(time.CLOCK_PROCESS_CPUTIME_ID)
    cv2_img = cv2.imread("/home/lz/Pictures/scene.jpg")
    print(time.clock_gettime(time.CLOCK_PROCESS_CPUTIME_ID) - tic)
    pp.imshow(jpeg_img)
    pp.show()
```
and it prints:
>0.04039233799999986
0.0016015890000000699

**Comment by ajkxyz** [comment]
1. `CLOCK_PROCESS_CPUTIME_ID` is the CPU time consumed by a current process, it can be different from real time in multicore environment (e.g. assume process uses 8 cores for 1 second => real time will be 1 second while process time will be 8 seconds) => better to use `time.monotonic()` if you are interested in real time.
2. When doing time measurement it is better to compute average time over several runs and exclude first run, because during the first run various initialization can happen.

I've modified your code:
```python
import cv2
import time
import jpeg4py as jpeg
import matplotlib.pyplot as pp
cv2.ocl.setUseOpenCL(False)
cv2.setNumThreads(0)


if __name__ == "__main__":
    K = 5
    t0 = time.monotonic()
    for i in range(K + 1):
        jpeg_img = jpeg.JPEG("1.jpg").decode()
        if not i:
            t0 = time.monotonic()
    dt = 1000.0 * (time.monotonic() - t0) / K
    print("libturbojpeg: %.3f ms" % dt)
    t0 = time.monotonic()
    for i in range(K + 1):
        cv2_img = cv2.imread("1.jpg")
        if not i:
            t0 = time.monotonic()
    dt = 1000.0 * (time.monotonic() - t0) / K
    print("OpenCV: %.3f ms" % dt)
    pp.imshow(jpeg_img)
    pp.show()
```
and for file 1024x684 got timings:
```console
libturbojpeg: 5.091 ms
OpenCV: 8.880 ms
```
=> opencv (4.2.0) is 1.74 times slower than libturbojpeg.

**Comment by laisimiao** [comment]
Oh, thank you for your reply!
